-- 社員テーブル。
--
-- これまでは spring.jpa.hibernate.ddl-auto=update に任せてテーブルを自動生成していたが、
-- それだと「いつ・誰が・何を変えたか」が残らず、本番のDBに何が適用済みなのかも分からない。
-- ここから先はテーブル定義の変更をすべてこのフォルダのSQLファイルとして残す（Flyway）。
--
-- 【重要】一度適用したファイルは編集しない。
-- Flyway は適用済みファイルのチェックサムを flyway_schema_history テーブルに記録しており、
-- 後から書き換えると次回起動時にエラーで止まる。直したいときは新しい V番号 のファイルを足す。

create table employee (
    id              bigint       generated by default as identity primary key,

    -- 業務キー。人が見て社員を識別する番号。
    -- アプリ側でも重複チェックしているが、DB側にも unique を付ける。
    -- アプリ側だけだと、2人が同時に登録したときにすり抜ける。
    employee_number varchar(10)  not null unique,

    name            varchar(50)  not null,
    name_kana       varchar(50)  not null,

    -- 区分値は enum の名前をそのまま文字列で持つ（EnumType.STRING）。
    -- 数値で持つと、あとで並び順を変えたときに既存データの意味が変わってしまう。
    department      varchar(20)  not null,

    email           varchar(100),
    hire_date       date         not null,
    status          varchar(20)  not null,
    note            varchar(200),

    -- いつ登録され、いつ更新されたか。業務系ではほぼ必須。
    created_at      timestamp    not null,
    updated_at      timestamp    not null
);

-- 一覧の既定の並び順が社員番号なので、索引を付けておく。
create index idx_employee_employee_number on employee (employee_number);

-- 部署・在籍区分での絞り込みと集計に使う。
create index idx_employee_department_status on employee (department, status);
