-- ログインする利用者のテーブル。
--
-- 「社員（employee）」とは別のテーブルにしている。
-- 社員はこのシステムを使わない人も含む名簿データで、利用者はシステムにログインする人。
-- 同じものとして扱うと、退職者を消せない・派遣の人にログインさせられない、といった問題が出る。

create table app_user (
    id           bigint      generated by default as identity primary key,

    username     varchar(50) not null unique,

    -- パスワードは絶対に平文で保存しない。BCrypt でハッシュ化した文字列を入れる。
    -- BCrypt の出力は60文字なので余裕を見て100。
    password     varchar(100) not null,

    display_name varchar(50) not null,

    -- 権限。ADMIN=登録・編集・削除ができる / VIEWER=閲覧とCSV出力のみ。
    role         varchar(20) not null,

    -- 退職・休職時にアカウントを止められるようにする。
    -- 行を削除すると「誰が操作したか」の記録から参照できなくなるため、消さずに無効化する。
    enabled      boolean     not null default true,

    created_at   timestamp   not null
);
